universe = vanilla
+ProjectName = "dscp"

container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/R_tidyverse_FITSio.sif

executable = job.sh
arguments = $(input) $(output)

transfer_input_files = job.R, job.sh, $(input)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 512MB
request_disk = 4096MB

output = logs/$(studio).out
error  = logs/$(studio).err
log    = logs/$(studio).log

queue studio, input, output from studios_jobs.txt
